// <auto-generated />
namespace Dream_Housing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Stablishing_One_2_Many_relationship_between_Properties_and_Feedbacks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stablishing_One_2_Many_relationship_between_Properties_and_Feedbacks));
        
        string IMigrationMetadata.Id
        {
            get { return "202407300847274_Stablishing_One_2_Many_relationship_between_Properties_and_Feedbacks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
